version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  weather_producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: weather_producer
    volumes:
      - ./cities.json:/app/cities.json  # Shared cities.json file
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - kafka-network

  weather_consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: weather_consumer
    depends_on:
      - kafka
    env_file:
      - .env
    volumes:
      - ./cities.json:/app/cities.json  # Correctly bind-mount cities.json
    networks:
      - kafka-network

  weather_dashboard:
    container_name: weather_dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ./cities.json:/app/cities.json
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: always
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  kafka-network:
    driver: bridge